name: book_store
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  connectivity_plus: ^2.3.7
  cupertino_icons: ^1.0.2
  firebase_messaging: ^13.0.3
  firebase_core: ^1.2.1
  flutter_local_notifications: ^9.5.3+1
  fluttertoast: ^8.0.9
  flutter_typeahead: ^4.0.0
  get: ^4.6.1
  http: ^0.13.5
  image_compression_flutter: ^1.0.2
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  path_provider: ^2.0.8
  phone_number: ^0.12.0+1
  photo_view: ^0.14.0
  pin_code_fields: ^7.3.0
  pointer_interceptor: ^0.9.0+1
  shared_preferences: ^2.0.15
  shimmer_animation: ^2.1.0+1
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
